"""First Migration

Revision ID: 7f7581d2d845
Revises: 78bfcd5824c2
Create Date: 2021-10-30 12:52:05.872809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7581d2d845'
down_revision = '78bfcd5824c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('original_url', sa.Text(), nullable=True))
    op.add_column('urls', sa.Column('short_url', sa.Integer(), nullable=True))
    op.drop_column('urls', 's_url')
    op.drop_column('urls', 'o_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('o_url', sa.TEXT(), nullable=True))
    op.add_column('urls', sa.Column('s_url', sa.INTEGER(), nullable=True))
    op.drop_column('urls', 'short_url')
    op.drop_column('urls', 'original_url')
    # ### end Alembic commands ###
